<!DOCTYPE html>
<!-- saved from url=(0037)https://en.wikipedia.org/wiki/Website -->
<html class="client-js ve-available" lang="en" dir="ltr"><head><meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<script src="https://kit.fontawesome.com/yourcode.js" crossorigin="anonymous"></script>
<link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css" rel="stylesheet">
<link rel="stylesheet" href="C:\Users\i52352\Desktop\website\wikistyle.css">
<script language="JavaScript" type="text/javascript" src="/js/jquery-1.2.6.min.js"></script>
<script language="JavaScript" type="text/javascript" src="/js/jquery-ui-personalized-1.5.2.packed.js"></script>
<script language="JavaScript" type="text/javascript" src="/js/sprinkle.js"></script>
<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>

<title>Website - Wikipedia</title>
<script>document.documentElement.className="client-js";RLCONF={"wgBreakFrames":!1,"wgSeparatorTransformTable":["",""],"wgDigitTransformTable":["",""],"wgDefaultDateFormat":"dmy","wgMonthNames":["","January","February","March","April","May","June","July","August","September","October","November","December"],"wgRequestId":"39588450-e132-49d8-a49e-3caf801689d1","wgCSPNonce":!1,"wgCanonicalNamespace":"","wgCanonicalSpecialPageName":!1,"wgNamespaceNumber":0,"wgPageName":"Website","wgTitle":"Website","wgCurRevisionId":1023688577,"wgRevisionId":1023688577,"wgArticleId":33898,"wgIsArticle":!0,"wgIsRedirect":!1,"wgAction":"view","wgUserName":null,"wgUserGroups":["*"],"wgCategories":["Wikipedia indefinitely semi-protected pages","Use dmy dates from May 2020","Articles with short description","Short description matches Wikidata","Wikipedia articles with BNE identifiers","Wikipedia articles with BNF identifiers","Wikipedia articles with GND identifiers",
"Wikipedia articles with LCCN identifiers","Wikipedia articles with LNB identifiers","Websites"],"wgPageContentLanguage":"en","wgPageContentModel":"wikitext","wgRelevantPageName":"Website","wgRelevantArticleId":33898,"wgIsProbablyEditable":!1,"wgRelevantPageIsProbablyEditable":!1,"wgRestrictionEdit":["autoconfirmed"],"wgRestrictionMove":["sysop"],"wgFlaggedRevsParams":{"tags":{"status":{"levels":-1}}},"wgMediaViewerOnClick":!0,"wgMediaViewerEnabledByDefault":!0,"wgPopupsFlags":10,"wgVisualEditor":{"pageLanguageCode":"en","pageLanguageDir":"ltr","pageVariantFallbacks":"en"},"wgMFDisplayWikibaseDescriptions":{"search":!0,"nearby":!0,"watchlist":!0,"tagline":!1},"wgWMESchemaEditAttemptStepOversample":!1,"wgULSCurrentAutonym":"English","wgNoticeProject":"wikipedia","wgCentralAuthMobileDomain":!1,"wgEditSubmitButtonLabelPublish":!0,"wgULSPosition":"interlanguage","wgGENewcomerTasksGuidanceEnabled":!0,"wgGEAskQuestionEnabled":!1,
"wgGELinkRecommendationsFrontendEnabled":!1,"wgWikibaseItemId":"Q35127"};RLSTATE={"ext.globalCssJs.user.styles":"ready","site.styles":"ready","noscript":"ready","user.styles":"ready","ext.globalCssJs.user":"ready","user":"ready","user.options":"loading","ext.cite.styles":"ready","skins.vector.styles.legacy":"ready","jquery.makeCollapsible.styles":"ready","ext.visualEditor.desktopArticleTarget.noscript":"ready","ext.uls.interlanguage":"ready","ext.wikimediaBadges":"ready","wikibase.client.init":"ready"};RLPAGEMODULES=["ext.cite.ux-enhancements","site","mediawiki.page.ready","jquery.makeCollapsible","mediawiki.toc","skins.vector.legacy.js","ext.gadget.ReferenceTooltips","ext.gadget.charinsert","ext.gadget.extra-toolbar-buttons","ext.gadget.refToolbar","ext.gadget.switcher","ext.centralauth.centralautologin","mmv.head","mmv.bootstrap.autostart","ext.popups","ext.visualEditor.desktopArticleTarget.init","ext.visualEditor.targetLoader","ext.eventLogging","ext.wikimediaEvents",
"ext.navigationTiming","ext.uls.compactlinks","ext.uls.interface","ext.cx.eventlogging.campaigns","ext.centralNotice.geoIP","ext.centralNotice.startUp","ext.growthExperiments.SuggestedEditSession"];</script>

<script src="wiki.js"></script>
<link href="wiki.css" rel="stylesheet">

<h2><span class="mw-headline" id="History">History</span></h2>
<div role="note" class="hatnote navigation-not-searchable">Main article: <a href="https://en.wikipedia.org/wiki/History_of_the_World_Wide_Web" title="History of the World Wide Web">History of the World Wide Web</a></div>
<div class="thumb tright"><div class="thumbinner" style="width:242px;"><a href="https://en.wikipedia.org/wiki/File:NASA_Website_Homepage_-_April_25,_2015.png" class="image"></a>  <div class="thumbcaption"><div class="magnify"</div>The <a href="https://en.wikipedia.org/wiki/NASA" title="NASA">nasa.gov</a> <a href="https://en.wikipedia.org/wiki/Home_page" title="Home page">home page</a> in 2015</div></div></div>
<p>The <a href="https://en.wikipedia.org/wiki/World_Wide_Web" title="World Wide Web">World Wide Web</a> (WWW) was created in 1990 by the British CERN physicist <a href="https://en.wikipedia.org/wiki/Tim_Berners-Lee" title="Tim Berners-Lee">Tim Berners-Lee</a>.<sup id="cite_ref-First_page_1-0" class="reference"><a href="https://en.wikipedia.org/wiki/Website#cite_note-First_page-1">[1]</a></sup> On 30 April 1993, <a href="https://en.wikipedia.org/wiki/CERN" title="CERN">CERN</a> announced that the World Wide Web would be free to use for anyone, contributing to the immense growth of the Web.<sup id="cite_ref-w3c_2-0" class="reference"><a href="https://en.wikipedia.org/wiki/Website#cite_note-w3c-2">[2]</a></sup> Before the introduction of the <a href="https://en.wikipedia.org/wiki/Hypertext_Transfer_Protocol" title="Hypertext Transfer Protocol">Hypertext Transfer Protocol</a> (HTTP), other protocols such as <a href="https://en.wikipedia.org/wiki/File_Transfer_Protocol" title="File Transfer Protocol">File Transfer Protocol</a> and the <a href="https://en.wikipedia.org/wiki/Gopher_protocol" class="mw-redirect" title="Gopher protocol">gopher protocol</a> were used to retrieve individual files from a server. These protocols offer a simple <a href="https://en.wikipedia.org/wiki/Directory_structure" title="Directory structure">directory structure</a> which the user navigates and where they choose files to download. Documents were most often presented as plain text files without formatting or were encoded in <a href="https://en.wikipedia.org/wiki/Word_processor" title="Word processor">word processor</a> formats.
</p>
<h2><span class="mw-headline" id="Overview">Overview</span></h2>
<p>Websites can be used in various fashions: a personal website, a corporate website for a company, a government website, an organization website, etc. Websites can be the work of an individual, a business or other organization, and are typically dedicated to a particular topic or purpose. Any website can contain a <a href="https://en.wikipedia.org/wiki/Hyperlink" title="Hyperlink">hyperlink</a> to any other website, so the distinction between individual sites, as perceived by the user, can be blurred.
</p><p>Some websites require user registration or <a href="https://en.wikipedia.org/wiki/Subscription" class="mw-redirect" title="Subscription">subscription</a> to access content. Examples of <a href="https://en.wikipedia.org/wiki/Paywall" title="Paywall">subscription websites</a> include many business sites, news websites, <a href="https://en.wikipedia.org/wiki/Academic_journal" title="Academic journal">academic journal</a> websites, gaming websites, file-sharing websites, <a href="https://en.wikipedia.org/wiki/Internet_forum" title="Internet forum">message boards</a>, web-based <a href="https://en.wikipedia.org/wiki/Email" title="Email">email</a>, <a href="https://en.wikipedia.org/wiki/Social_networking" class="mw-redirect" title="Social networking">social networking</a> websites, websites providing real-time <a href="https://en.wikipedia.org/wiki/Stock_market" title="Stock market">stock market</a> data, as well as sites providing various other services.
</p><p>While "web site" was the original spelling (sometimes capitalized "Web site", since "Web" is a proper noun when referring to the <a href="https://en.wikipedia.org/wiki/World_Wide_Web" title="World Wide Web">World Wide Web</a>), this variant has become rarely used, and "website" has become the standard spelling. All major style guides, such as <i><a href="https://en.wikipedia.org/wiki/The_Chicago_Manual_of_Style" title="The Chicago Manual of Style">The Chicago Manual of Style</a></i><sup id="cite_ref-3" class="reference"><a href="https://en.wikipedia.org/wiki/Website#cite_note-3">[3]</a></sup> and the <i><a href="https://en.wikipedia.org/wiki/AP_Stylebook" title="AP Stylebook">AP Stylebook</a></i>,<sup id="cite_ref-AP_tweet_4-0" class="reference"><a href="https://en.wikipedia.org/wiki/Website#cite_note-AP_tweet-4">[4]</a></sup> have reflected this change.
</p>

<!-- <div ng-repeat="file in imagefinaldata" class="img_wrp"> -->
<!-- <img src="New_Logo_AD.jpg" id="adLogo"> -->
<!-- <img src="iconclose.jpg" id="closeLogo"> -->
<!-- </div> -->

<h2><span class="mw-headline" id="Static_website">Static website</span></h2>
<div role="note" class="hatnote navigation-not-searchable">Main article: <a href="https://en.wikipedia.org/wiki/Static_web_page" title="Static web page">Static web page</a></div>
<p>A static website is one that has web pages stored on the server in the format that is sent to a client web browser. It is primarily coded in <a href="https://en.wikipedia.org/wiki/Hypertext_Markup_Language" class="mw-redirect" title="Hypertext Markup Language">Hypertext Markup Language</a> (HTML); <a href="https://en.wikipedia.org/wiki/Cascading_Style_Sheets" class="mw-redirect" title="Cascading Style Sheets">Cascading Style Sheets</a> (CSS) are used to control appearance beyond basic HTML.  Images are commonly used to create the desired appearance and as part of the main content.  Audio or video might also be considered "static" content if it plays automatically or is generally non-interactive. This type of website usually displays the same information to all visitors. Similar to handing out a printed brochure to customers or clients, a static website will generally provide consistent, standard information for an extended period of time. Although the website owner may make updates periodically, it is a manual process to edit the text, photos, and other content and may require basic website design skills and software.  Simple forms or marketing examples of websites, such as <i>classic website</i>, a <i>five-page website</i> or a <i>brochure website</i> are often static websites, because they present pre-defined, static information to the user. This may include information about a company and its products and services through text, photos, animations, audio/video, and navigation menus.

</div>
